### ISSUE TITLE
[Multi-monitor] Add option to disable full screen snapping on portrait setups

### ISSUE THREAD

**Issue by Turbine1991** [Leleat/Tiling-Assist#43]
**Describe your idea**
Hi, I've just set up my dual screen setup.

One feature which appears strange in portrait mode is that it's difficult to vertically tile due to the full screen gesture.

What works for landscape should work for the longest edge in portrait mode. As some people might want the full screen gesture, I think such a feature would be best in the settings panel.

**Additional context**
As it doesn't make sense to disable this on landscape (default), perhaps limiting the setting to only screens with landscape activated or select screens to activate it on.

**Comment by Turbine1991** [comment]
I'm currently working on a pull request to implement this feature.

**Comment by Leleat** [comment]
> One feature which appears strange in portrait mode is that it's difficult to vertically tile due to the full screen gesture.

There was a bug with the top half detection so maybe you were hit by that. I pushed a commit to fix it a couple days ago (but I've just noticed that I overlooked one part, so I updated the commit now).

> Hovering at the top for a period will then trigger a fullscreen action

Time-based switching between top half & maximize tiling sounds better than the current position based approach.

> when the setting is enabled.

How did you imagine it to work / what is the setting called? I don't mind, if you don't introduce a setting at all and just change the current behaviour, so it's conistent for all monitors. However `maximize` should be the default then and `half tiling` should be appearing after the timer, because, as you said, landscape is the default orientation. `Maximize` is a lot more useful then. 

Even on vertical screens people may prefer `maximize` depending on what they do. For example, coders can benefit from the additional vertical space to see more lines. Browsers (/websites) probably also benefit more from `maximize` since content scrolls vertically...

**Comment by Turbine1991** [comment]
> There was a bug with the top half detection so maybe you were hit by that. I pushed a commit to fix it a couple days ago (but I've just noticed that I overlooked one part, so I updated the commit now).

I did notice this, I'm glad it's solved. It's unrelated to why I say it's difficult to vertically tile in portrait.

> Time-based switching between half tiling & maximize tiling sounds better than the current position-based approach.

Good idea, replacing the awkward current window top-half placement would solve the difficulty of half tiling in portrait mode. (The snap zone is a lot smaller than on landscape)

> How did you imagine it to work / what is the setting called? I don't mind, if you don't introduce a setting at all and just change the current behaviour, so it's conistent for all monitors. However maximize should be the default then and half tiling should be appearing after the timer, because, as you said, landscape is the default orientation. Maximize is a lot more useful then.

Well how about this then.
- By default maximise is still the same, except that you can use the rest of the top screen previously dedicated to half-tiling.
- By default holding at the top will trigger half tiling, across all moniors.
- Add a setting to inverse this behavour across all monitors. To make top snapping consistent with bottom snapping. Many might prefer this bahaviour as we already have double clicking to quickly maximise.
- Add another setting to only inverse on portrait monitors. Because depending on your work type (programming vs browsing), half-tiling does for some reason feel more natural on the lengthiest edge.

**Comment by Leleat** [comment]
> - By default maximise is still the same, except that you can use the rest of the top screen previously dedicated to half
> - By default holding at the top will trigger half tiling, across all moniors.
> - Add a setting to inverse this behavour across all monitors. To make top snapping consistent with bottom snapping. Many might prefer this bahaviour as we already have double clicking to quickly maximise.
> - Add another setting to only inverse on portrait monitors. Because depending on your work type (programming vs browsing), half-tiling does for some reason feel more natural on the lengthiest edge.

I like the first 3. Not a fan of the 4th. Dragging the window to the top is (at least to me) a no-thinking reflex/action. So having its behaviour change depending on the monitor, might create unintended tiling incidents every now and then because I didn't think about it when just dragging the window to the top... Well, as long as you turn that settings off by default, I don't mind adding it though.

**Comment by Turbine1991** [comment]
> Well, as long as you turn that settings off by default, I don't mind adding it though.
Yeah, it will be off by default, for consistency. Different workloads suit different settings, not to mention portrait  monitors can change your workload.
